# Default values for metrics-server-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: metrics-server-migration
namespace: kube-system

image:
  registry: quay.io
  repository: giantswarm/k8s-migrator
  tag: latest

resources:
  limits:
    cpu: 50m
    memory: 75Mi
  requests:
    cpu: 50m
    memory: 75Mi

