{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: {{ .Values.serviceType }}
    k8s-app: {{ .Values.k8sAppLabel }}
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
    - nodes/stats
    verbs:
    - get
    - create
{{- end -}}
