apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: {{ .Values.serviceType }}
    k8s-app: {{ .Values.k8sAppLabel }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    k8s-app: {{ .Values.k8sAppLabel }}
